module Stroma
  module Hooks
    class Factory
      @hooks: Collection
      @matrix: Matrix

      def initialize: (Collection hooks, Matrix matrix) -> void

      def wrap: (Symbol key, *Module extensions) -> void

      private

      def validate_key!: (Symbol key) -> void
    end
  end
end
