module Stroma
  class Registry
    @matrix_name: Symbol
    @entries: Array[Entry]
    @finalized: bool

    attr_reader matrix_name: Symbol

    def initialize: (Symbol | String matrix_name) -> void

    def register: (Symbol | String key, Module extension) -> void

    def finalize!: () -> void

    def entries: () -> Array[Entry]

    def keys: () -> Array[Symbol]

    def key?: (Symbol | String key) -> bool

    private

    def ensure_finalized!: () -> void
  end
end
